gitk: Update cherry-pick error message parsing
Commit cc9fccd7c7ea4ff26fe0d8dc869327ab91e99ca5 [formerly 981ff5c37ae20687c98d98c8689d5e89016026d2] changed the error
message from git cherry-pick from
    Automatic cherry-pick failed.  [...advice...]
to
    error: could not apply 7ab78c9... Do something neat.
    [...advice...]

Update gitk’s regex to match this, restoring the ability to launch git
citool to resolve conflicted cherry-picks.

Signed-off-by: Anders Kaseorg <andersk@mit.edu>
Signed-off-by: Paul Mackerras <paulus@samba.org>

Former-commit-id: b74307f6a551d50e9b1aa121a326d32ff1827a93